#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the DXHUB usb connection as /dev/r_dxhub and /dev/l_dxhub."
echo "This may require password."
echo ""

sudo cp `rospack find jsk_2016_01_baxter_apc`/firmware/udev/80-dxhub.rules /etc/udev/rules.d

echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
