#!/usr/bin/env bash

set -eu

[[ ${DOCKER_TAG} =~ ([a-z]+)-([0-9a-z.]+)$ ]]
if [[ ${BASH_REMATCH[2]} = "testing" ]]; then
  [[ ${DOCKER_TAG} =~ ([a-z]+)-([0-9a-z.]+)-([a-z]+)$ ]];
  ROS_DISTRO=${BASH_REMATCH[1]};
  TESTING="true"
else
  ROS_DISTRO=${BASH_REMATCH[1]};
  TESTING="false"
fi

if [[ ${ROS_DISTRO} = "noetic" ]]; then
    UBUNTU_VERSION="focal";
elif [[ ${ROS_DISTRO} = "melodic" ]]; then
    UBUNTU_VERSION="bionic";
elif [[ ${ROS_DISTRO} = "kinetic" ]]; then
    UBUNTU_VERSION="xenial";
elif [[ ${ROS_DISTRO} = "indigo" ]]; then
    UBUNTU_VERSION="trusty";
fi

docker build --build-arg ROS_DISTRO=${ROS_DISTRO} \
             --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
             --build-arg TESTING=${TESTING} \
             -t ${IMAGE_NAME} .
