#!/bin/bash

echo ""
echo "This script copies udev rules for grippers and their dependencies"
echo "to /etc/udev/rules.d and /usr/local/sbin"
echo ""

sudo cp `rospack find sphand_driver`/udev/60-i2c.rules /etc/udev/rules.d
sudo cp `rospack find sphand_driver`/udev/70-spi.rules /etc/udev/rules.d
sudo cp `rospack find sphand_driver`/udev/80-dxhub.rules /etc/udev/rules.d
sudo cp `rospack find sphand_driver`/udev/90-gpio.rules /etc/udev/rules.d

echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
