from grasp_data_generator.evaluations.eval_grasp_segmentation import eval_grasp_segmentation  # NOQA
from grasp_data_generator.evaluations.eval_instance_segmentation_voc import eval_instance_segmentation_voc  # NOQA
from grasp_data_generator.evaluations.eval_semantic_segmentation import eval_semantic_segmentation  # NOQA
