;; -*- mode: lisp;-*-

(require "package://jsk_2015_05_baxter_apc/euslisp/motion/move-to-target-bin.l")
(require "package://jsk_2015_05_baxter_apc/euslisp/motion/move-for-verification.l")
(require "package://jsk_2015_05_baxter_apc/euslisp/motion/pick-object.l")
(require "package://jsk_2015_05_baxter_apc/euslisp/motion/return-object.l")
(require "package://jsk_2015_05_baxter_apc/euslisp/motion/place-object.l")
