;; about work order
(load "package://jsk_2014_picking_challenge/euslisp/motion/get-work-order.l")
;; about vacuum gripper
(load "package://jsk_2014_picking_challenge/euslisp/motion/control-vacuum-gripper.l")
(load "package://jsk_2014_picking_challenge/euslisp/motion/check-if-grabbed.l")
;; about baxter arm motions
(load "package://jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l")
(load "package://jsk_2014_picking_challenge/euslisp/motion/move-for-verification.l")
(load "package://jsk_2014_picking_challenge/euslisp/motion/pick-object.l")
(load "package://jsk_2014_picking_challenge/euslisp/motion/return-object.l")
(load "package://jsk_2014_picking_challenge/euslisp/motion/place-object.l")
;; about object verification
(load "package://jsk_2014_picking_challenge/euslisp/motion/verify-object.l")
;; others
(load "package://jsk_2014_picking_challenge/euslisp/motion/tweet.l")