<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="right_vaccum_gripper">
  <xacro:include filename="$(find jsk_2016_01_baxter_apc)/robots/common_constants.xacro"/>
  <!-- Gazebo Tags -->
  <gazebo reference="right_gripper_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="right_gripper_vacuum_pad_base">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_gripper_vacuum_pad">
    <selfCollide>true</selfCollide>
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="right_gripper_vacuum_pad_joint">
    <implicitSpringDamper>false</implicitSpringDamper>
  </gazebo>
  <!--Link bodies-->
  <xacro:property name="rect_tube_l" value="0.285" />
  <xacro:property name="rect_tube_h" value="0.06" />
  <xacro:property name="rect_tube_w" value="0.0952" />
  <xacro:property name="cyl_tube_x" value="0.005" />
  <xacro:property name="cyl_tube_z" value="0.038" />
  <xacro:property name="cyl_tube_r" value="0.018" />
  <xacro:property name="cyl_tube_l" value="0.107" />
  <xacro:property name="connection_z" value="-0.00725" />
  <xacro:property name="connection_r" value="0.03" />
  <xacro:property name="connection_l" value="0.0905" />
  <xacro:property name="pad_base_z" value="0.025" />
  <xacro:property name="pad_base_w" value="0.09" />
  <xacro:property name="pad_base_h" value="0.038" />
  <xacro:property name="pad_base_d" value="0.06" />
  <xacro:property name="pad_r" value="0.026" />
  <xacro:property name="pad_l" value="0.03" />
  <xacro:property name="pad_x" value="-0.0005" />
  <xacro:property name="pad_y" value="0.0085" />
  <xacro:property name="pad_z" value="0.07" />
  <!--Joints-->
  <xacro:property name="right_hand_offset_x" value="-0.01" />
  <xacro:property name="right_hand_offset_z" value="0" />
  <xacro:property name="right_gripper_joint_offset_x" value="0.005" />
  <xacro:property name="right_gripper_joint_offset_y" value="-0.0085" />
  <xacro:property name="right_gripper_joint_offset_z" value="0.264" />

  <link name="right_gripper_base">
    <visual>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/visual/right_gripper_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <!--When using this stl file, robot_self_filter doesn't work-->
    <!--<collision>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/collision/right_gripper_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>-->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${rect_tube_l/2}"/>
      <geometry>
        <box size="${rect_tube_h} ${rect_tube_w} ${rect_tube_l}"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="${M_PI/2} 0 0" xyz="${cyl_tube_x} -${cyl_tube_l/2} ${cyl_tube_z}"/>
      <geometry>
        <cylinder radius="${cyl_tube_r}" length="${cyl_tube_l}"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0 0 0" xyz="${cyl_tube_x} -${cyl_tube_l} ${connection_z}"/>
      <geometry>
        <cylinder radius="${connection_r}" length="${connection_l}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_vacuum_pad_base">
    <visual>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/visual/right_gripper_vacuum_pad_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <!--When using this stl file, robot_self_filter doesn't work-->
    <!--<collision>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/collision/right_gripper_vacuum_pad_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>-->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${pad_base_z}"/>
      <geometry>
        <box size="${pad_base_h} ${pad_base_w} ${pad_base_d}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  <link name="right_gripper_vacuum_pad">
    <visual>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/visual/right_gripper_vacuum_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <!--When using this stl file, robot_self_filter doesn't work-->
    <!--<collision>
      <origin rpy="${M_PI/2} 0 -${M_PI/2}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jsk_2016_01_baxter_apc/meshes/collision/right_gripper_vacuum_pad.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>-->
    <collision>
      <origin rpy="0 0 0" xyz="${pad_x} ${pad_y} ${pad_z}"/>
      <geometry>
        <cylinder radius="${pad_r}" length="${pad_l}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="right_gripper_base_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="${right_hand_offset_x} 0 ${right_hand_offset_z}" />
    <parent link="right_hand"/>
    <child link="right_gripper_base"/>
  </joint>
  <joint name="right_gripper_vacuum_pad_joint" type="revolute">
    <origin rpy="0 0 0" xyz="${right_gripper_joint_offset_x} ${right_gripper_joint_offset_y} ${right_gripper_joint_offset_z}" />
    <parent link="right_gripper_base"/>
    <child link="right_gripper_vacuum_pad_base"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.58" upper="1.58" effort="0" velocity="4.5"/>
  </joint>
  <joint name="right_gripper_vacuum_pad_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="right_gripper_vacuum_pad_base"/>
    <child link="right_gripper_vacuum_pad"/>
  </joint>

</robot>
