#!/usr/bin/env python

import rospy
from jsk_tools.sanity_lib import checkTopicIsPublished


def main():
    rospy.init_node('check_setup_sanity')
    checkTopicIsPublished(
        '/left_hand_camera/extract_indices_target_bin/output',
        timeout=5, echo=True, echo_noarr=True)
    checkTopicIsPublished(
        '/right_hand_camera/extract_indices_target_bin/output',
        timeout=5, echo=True, echo_noarr=True)


if __name__ == '__main__':
    main()
