#!/usr/bin/env python

import sys

from rqt_yn_btn.yes_no_button import YesNoButton
from rqt_gui.main import Main


plugin = 'rqt_yn_btn'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

