#!/usr/bin/env python

import sys

from rqt_yn_btn.my_module import MyPlugin
from rqt_gui.main import Main


plugin = 'rqt_yn_btn'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

